'<form id="login-form" action="/cgi-bin/%s/loginaction" method="post">' + sLineBreak +
'  <fieldset>' + sLineBreak +
'    <legend>Login</legend>' + sLineBreak +
'      <label for="login">E-mail: </label>' + sLineBreak +
'        <input type="text" id="login" name="login"/>' + sLineBreak +
'          <div class="clear"></div>' + sLineBreak +
'            <label for="password">Password: </label>' + sLineBreak +
'            <input type="password" id="password" name="password"/>' + sLineBreak +
'            <div class="clear"></div>' + sLineBreak +
'            <label for="remember_me" style="padding: 0;">Remember me</label>' + sLineBreak +
'            <input type="checkbox" id="remember_me" style="position: relative; top: 3px; margin: 0; " name="remember_me"/>' + sLineBreak +
'            <div class="clear"></div>' + sLineBreak +
'            <br />' + sLineBreak +
'            <input type="submit" style="margin: -20px 0 0 287px;" class="button" name="commit" value="Log in"/>' + sLineBreak +
'  </fieldset>' + sLineBreak +
'</form>';
