'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">' + sLineBreak +
'<html xmlns="http://www.w3.org/1999/xhtml">' + sLineBreak +
'<head>' + sLineBreak +
'  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />' + sLineBreak +
'    <title>%s</title>' + sLineBreak +
'      <link rel="stylesheet" type="text/css" href="%s" />' + sLineBreak +
'</head>' + sLineBreak +
'<body>' + sLineBreak +
'  %s' + sLineBreak +
'</body>' + sLineBreak +
'</html>';
